project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - projects/lulc-himalaya.qmd
    - projects/urban-typologies.qmd
    - projects/urban-growth-scenarios.qmd
    - projects/ecosystem-services.qmd
    - projects/planning-framework.qmd
    - projects/urban-heat-island.qmd
  

website:
  title: "Dr. Sonali Sharma"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: "index.qmd#projects"
      - text: "Experience"
        href: "index.qmd#experience"
      - text: "Publications"
        href: "index.qmd#publications"
      - text: "Contact"
        href: "index.qmd#contact"
    right:
      - icon: github
        href: https://github.com/sonalispatial18/sonali-geo
      - icon: linkedin
        href: https://www.linkedin.com/in/sonali-sharma-50220210b/

format:
  html:
    theme: flatly
    toc: false
    css: styles.css
    page-layout: full

execute:
  freeze: auto
  enabled: false

jupyter: false